import os
API_ID = os.environ.get("API_ID", None) 
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,"ChatsGpt7_bot") 
SUDO=os.environ.get("SUDO","6247852792")
BOT_NAME = os.environ.get("BOT_NAME","CHATGPT BOT")
START_IMG = os.environ.get("START_IMG","https://telegra.ph/file/07af95570dea3f4533f58.jpg")
STKR = os.environ.get("STKR","CAACAgEAAx0CRjAUHgABAsULZASkFZUsTQTw2k-FvC2SBJnd-vAAAokCAALW9iBFzemsQBDIqWkuBA")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL","Bots_Hub_ll")
# OWNER_USERNAME = os.environ.get("OWNER_USERNAME","ItzCodeR_XD7")
SUDO=os.environ.get("SUDO","6247852792")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","Daisy_Support_chat")
